name: Release Tag

on:
  push:
    tags: v*
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set Variables
      run: echo "release_version=${GITHUB_REF_NAME/v/}" >> $GITHUB_ENV

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.19'

    - name: Build
      run: go build -v

    - name: Test
      run: go test -v ./...

    - name: Package Binary
      run: rsync prometheus-filter-proxy README.md LICENSE prometheus-filter-proxy-${{ env.release_version }}-linux-amd64 && tar cvjf prometheus-filter-proxy-${{ env.release_version }}-linux-amd64.tar.bz2 prometheus-filter-proxy-${{ env.release_version }}-linux-amd64

    - name: Release
      uses: softprops/action-gh-release@c9b46fe7aad9f02afd89b12450b780f52dacfb2d
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          prometheus-filter-proxy-${{ env.release_version }}-linux-amd64.tar.bz2
